[tasks.coverage-linux]
workspace = false
script = ["cargo tarpaulin --workspace --all-features --tests --out Html"]

[tasks.coverage-mac]
workspace = false
script = '''
echo "*** Generating coverage: $pwd"
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Cinstrument-coverage -Copt-level=0 -Clink-dead-code"
export LLVM_PROFILE_FILE="target/coverage/profraw/project-%p-%m.profraw"
rm -rf target/coverage/profraw
cargo test --all --workspace
grcov target/coverage/profraw -s . --binary-path target/debug/ -t html --branch --ignore-not-existing -o target/coverage/
echo "*** Coverage report generated at target/coverage/html/index.html"
'''

[tasks.coverage]
description = "Run OS-specific coverage"
workspace = false
run_task = [
    { name = "coverage-linux", condition = { platforms = ["linux"] } },
    { name = "coverage-mac", condition = { platforms = ["mac"] } }
]
