[package]
name = "schema-migration-generator"
description.workspace = true
documentation = "https://docs.rs/schema-migration-generator"
homepage.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[[bin]]
name = "schema-migration-generator"
path = "src/main.rs"

[dependencies]
schema-model.workspace = true
schema-diff.workspace = true
schema-parser.workspace = true
thiserror = "2"
clap = "^4.5.50"
chrono = "0.4"
